name: Deploy to Oracle VPS

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/portfolio.madebysag.xyz
          git pull origin main
          
          # Optional: Add build or restart commands below depending on your stack
          # npm install --production
          # pm2 restart my-app
          # docker-compose up -d --build